import { useClerk, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { api } from "~/utils/api";

import Post from "~/components/Post";
import { UilMessage } from "@iconscout/react-unicons";
import PostField from "~/components/CreatePost";
import CreatePost from "~/components/CreatePost";

const Home = () => {
    const user = useUser();
    const router = useRouter();
    const { signOut } = useClerk();
    const { data } = api.posts.getAll.useQuery();
    const [toggleMenu, setToggleMenu] = useState<boolean>(false);

    const handleSignOut = () => {
        router.push("/").catch((err) => {
            console.error(err);
        });
        signOut().catch((err) => {
            console.error(err);
        });
    };

    useEffect(() => {
        if (!user.isSignedIn) {
            router.push("/").catch((err) => {
                console.error(err);
            });
        }
    }, []);

    if (!user.isLoaded) {
        return (
            <div className="h-screen w-screen">
                <h1>Loading</h1>
            </div>
        );
    }
    return (
        <div className="min-h-screen w-screen ">
            <Head>
                <title>Paperplane | Homepage</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="container mx-auto min-h-screen px-16">
                <div className="flex w-full items-center justify-between py-6">
                    <div className="flex items-center gap-2">
                        <UilMessage></UilMessage>
                        <h1 className="text-2xl font-bold">Paperplane.</h1>
                    </div>
                    <div className="relative flex flex-col items-end gap-2">
                        <div className="flex items-center gap-4">
                            <div className=" flex flex-col items-end">
                                <p className="text-md mb-[-4px]">Hello,</p>
                                <h1 className="text-xl font-bold">
                                    {user.user?.fullName}
                                </h1>
                            </div>
                            <Image
                                src={user.user?.profileImageUrl ?? ""}
                                alt="profile-image"
                                width={45}
                                height={45}
                                className="rounded-xl"
                                role="button"
                                onClick={() => setToggleMenu(!toggleMenu)}
                            ></Image>
                        </div>
                        <div
                            className={`absolute top-full mt-2 w-fit transition-transform duration-500 ${
                                toggleMenu
                                    ? "translate-x-[0]"
                                    : "translate-x-[500%]"
                            }`}
                        >
                            <button
                                className="duration-250 rounded-md border-2 border-zinc-600 bg-zinc-900 px-4 py-1 text-sm font-medium text-white transition-colors hover:bg-zinc-700"
                                onClick={() => handleSignOut()}
                            >
                                Sign Out
                            </button>
                        </div>
                    </div>
                </div>
                <div className="mt-8">
                    <CreatePost></CreatePost>
                </div>
                <div className="my-4 h-[2px] w-full bg-zinc-300"></div>
                <div className="flex flex-col gap-4">
                    {data?.map(({ post, author }) => (
                        <Post key={post.id} post={post} author={author}></Post>
                    ))}
                </div>
            </main>
        </div>
    );
};

export default Home;
