import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";
import { BiPencil } from "react-icons/bi";
import { useRouter } from "next/router";
import { Spinner } from "~/components";

const EditProfile = () => {
    const user = useUser();
    const router = useRouter();
    const [firstName, setFirstName] = useState("");
    const [lastName, setLastName] = useState("");
    const [username, setUsername] = useState("");

    const [isEditingFN, setIsEditingFN] = useState(false);
    const [isEditingLN, setIsEditingLN] = useState(false);
    const [isEditingUN, setIsEditingUN] = useState(false);

    const handleUpdateProfile = () => {
        user.user
            ?.update({
                // firstName: firstName,
                // lastName: lastName,
                username: username,
            })
            .then(() => {
                alert("Update Success");
            })
            .catch((err) => {
                console.error(err);
            });
    };

    useEffect(() => {
        if (firstName === "") setFirstName(user.user?.firstName ?? "");
        if (lastName === "") setLastName(user.user?.lastName ?? "");
        if (username === "") setUsername(user.user?.username ?? "");
    }, [user]);

    useEffect(() => {
        if (!user.isSignedIn && user.isLoaded) {
            router.push("/").catch((err) => {
                console.error(err);
            });
        }
    }, []);

    if (!user.isLoaded) {
        return (
            <div className="flex h-screen w-screen items-center justify-center">
                <Spinner></Spinner>
            </div>
        );
    }

    return (
        <div>
            <Head>
                <title>Paperplane | Homepage</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 className="mt-8 text-2xl font-bold md:my-0">Edit Profile</h1>
            <div className="w-fit items-center gap-12 py-4">
                <Image
                    src={user.user?.profileImageUrl ?? ""}
                    alt="profile-image"
                    width={150}
                    height={150}
                    className="rounded-2xl"
                ></Image>
                <div className="mt-5">
                    <div className="flex gap-12">
                        <div className="text-lg font-bold">
                            <h2 className="py-2">First Name</h2>
                            <h2 className="py-2">Last Name</h2>
                            <h2 className="py-2">Username</h2>
                        </div>
                        <div className="text-lg">
                            <div
                                className="group flex cursor-pointer items-center gap-2 py-2"
                                onClick={() => setIsEditingFN(true)}
                            >
                                <p
                                    className={` ${
                                        isEditingFN ? "hidden" : "block"
                                    }`}
                                >
                                    {firstName}
                                </p>
                                <input
                                    type="text"
                                    value={firstName ?? ""}
                                    className={`px-2 ${
                                        isEditingFN ? "block" : "hidden"
                                    }`}
                                    onChange={(e) =>
                                        setFirstName(e.target.value)
                                    }
                                    onBlur={() => setIsEditingFN(false)}
                                />
                                <i className="duration-250 opacity-0 transition-opacity group-hover:opacity-75">
                                    <BiPencil></BiPencil>
                                </i>
                            </div>
                            <div
                                className="group flex cursor-pointer items-center gap-2 py-2"
                                onClick={() => setIsEditingLN(true)}
                            >
                                <p
                                    className={` ${
                                        isEditingLN ? "hidden" : "block"
                                    }`}
                                >
                                    {lastName}
                                </p>
                                <input
                                    type="text"
                                    value={lastName ?? ""}
                                    className={`px-2 ${
                                        isEditingLN ? "block" : "hidden"
                                    }`}
                                    onChange={(e) =>
                                        setLastName(e.target.value)
                                    }
                                    onBlur={() => setIsEditingLN(false)}
                                />
                                <i className="duration-250 opacity-0 transition-opacity group-hover:opacity-75">
                                    <BiPencil></BiPencil>
                                </i>
                            </div>
                            <div
                                className="group flex cursor-pointer items-center gap-2 py-2"
                                onClick={() => setIsEditingUN(true)}
                            >
                                <p
                                    className={` ${
                                        isEditingUN ? "hidden" : "block"
                                    }`}
                                >
                                    {username}
                                </p>
                                <input
                                    type="text"
                                    value={username ?? ""}
                                    className={`px-2 ${
                                        isEditingUN ? "block" : "hidden"
                                    }`}
                                    onChange={(e) =>
                                        setUsername(e.target.value)
                                    }
                                    onBlur={() => setIsEditingUN(false)}
                                />
                                <i className="duration-250 opacity-0 transition-opacity group-hover:opacity-75">
                                    <BiPencil></BiPencil>
                                </i>
                            </div>
                        </div>
                    </div>
                    <button
                        onClick={() => {
                            handleUpdateProfile();
                        }}
                        className="duration-250 mt-4 rounded-md border-2 border-zinc-600 bg-zinc-900 px-4 py-1 text-sm font-medium text-white transition-colors hover:bg-zinc-700"
                    >
                        Update Profile
                    </button>
                </div>
            </div>
        </div>
    );
};

export default EditProfile;
