/* eslint-disable react-hooks/exhaustive-deps */
import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect } from "react";
import { CreatePost, Post, Spinner } from "~/components";
import { api } from "~/utils/api";

const Home = () => {
    const user = useUser();
    const router = useRouter();
    const { data, isLoading } = api.posts.getAllPosts.useQuery();

    useEffect(() => {
        if (!user.isSignedIn && user) {
            router.push("/").catch((err) => {
                console.error(err);
            });
        }
    }, []);

    if (!user.isLoaded) {
        return (
            <div className="flex h-screen w-screen items-center justify-center">
                <Spinner></Spinner>
            </div>
        );
    }
    return (
        <>
            <Head>
                <title>Paperplane | Homepage</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="mt-4 md:mt-0">
                <CreatePost></CreatePost>
            </div>
            <div className="my-4 h-[1px] w-full bg-zinc-200"></div>
            {isLoading ? (
                <div className="flex w-full justify-center">
                    <Spinner></Spinner>
                </div>
            ) : (
                <div className="flex h-[68vh] flex-col gap-4 overflow-y-auto md:h-[66vh]">
                    {data?.map(({ post, author }) => (
                        <Post key={post.id} post={post} author={author}></Post>
                    ))}
                </div>
            )}
        </>
    );
};

export default Home;
