import { useClerk, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect } from "react";
import { api } from "~/utils/api";

const Home = () => {
    const user = useUser();
    const router = useRouter();
    const { signOut } = useClerk();
    const { data } = api.posts.getAll.useQuery();

    const handleSignOut = () => {
        signOut().catch((err) => {
            console.error(err);
        });
        router.push("/").catch((err) => {
            console.error(err);
        });
    };

    useEffect(() => {
        if (!user.isSignedIn) {
            router.push("/").catch((err) => {
                console.error(err);
            });
        }
    }, []);

    console.log(data);
    if (!user.isLoaded) {
        return (
            <div className="h-screen w-screen">
                <h1>Loading</h1>
            </div>
        );
    }
    return (
        <div className="min-h-screen w-screen ">
            <Head>
                <title>Learning-T3 | Login</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="container mx-auto min-h-screen px-16">
                <div className="flex w-full items-center justify-between py-6">
                    <h1 className="text-xl">
                        Hello,{" "}
                        <span className="font-medium">
                            {user.user?.fullName}
                        </span>
                    </h1>
                    <button
                        className="duration-250 rounded-md border-2 border-sky-400 bg-sky-500 px-4 py-1 text-sm font-medium text-white transition-colors hover:border-sky-500 hover:bg-sky-400"
                        onClick={() => handleSignOut()}
                    >
                        Sign Out
                    </button>
                </div>
                <div></div>
                <div>
                    <div>
                        {data?.map((post) => (
                            <div
                                key={post.id}
                                className="border-b-[0.2px] border-black last:border-b-0"
                            >
                                {post.content}
                            </div>
                        ))}
                    </div>
                </div>
            </main>
        </div>
    );
};

export default Home;
